leveling:
    power: 1.0
    maxExperience: 100000
    maxLevel: 50
    expLoss: 0.5
    max-tracked-blocks: 2000
    block-tracking-duration: 900000
    resetExpOnClassChange: true
    swapMasteryCost: false
    partyBonus: 0.20
properties:
    iConomy: false
    swapcost: 0
    debug: false
    useDamageSystem: true
bed:
    bedHeal: true
    healInterval: 30
    healPercent: 5