leveling:
    power: 1.0
    maxExperience: 100000
    maxLevel: 50
    expLoss: 0.5
    max-tracked-blocks: 2000
    block-tracking-duration: 900000
    resetExpOnClassChange: true
properties:
    iConomy: false
    swapcost: 250
    debug: false