name: Heroes
main: com.herocraftonline.dev.heroes.Heroes
version: 1.1.2
website: http://www.herocraftonline.com
authors: [DThielke, Rigby, RightLegRed, Kainzo]
description: Experience, leveling and class system for Minecraft developed by the Herocraft coding team.
softdepend: [Permissions, BukkitContrib, BOSEconomy, iConomy]
commands:
  heroes:
    aliases: ['hero']
    description: Heroes commands
    usage: /<command>
  hrecover:
    description: Heroes Recover Items command
    usage: /<command>
  party:
    aliases: ['p']
    description: Heroes command
    usage: /<command> <message>
  skill:
    aliases: ['hskill']
    description: Heroes command
    usage: /<command> <skill>
  skills:
    aliases: ['skilllist']
    description: Heroes command
    usage: /<command>
  hlevel:
    aliases: ['level','lvl']
    description: Display Hero level information
    usage: /<command>
  bind:
    description: Binds a skill to an item
    usage: /<command> <skill> 
  mana:
    description: Displays the hero's current mana
    usage: /<command>
  health:
    aliases: [hp]
    description: Displays the hero's health
    usage: /<command>
  party:
    aliases: ['p','pc']
    description: Chat with Heroes party members
    usage: /<command> <message>
  confirm:
    description: Confirms a command
    usage: /<command>
  cancel:
    description: Cancels a command
    usage: /<command>